// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kaiju/entity/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryEntityListRequest struct {
	EntityType   string `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty" yaml:"entity_type"`
	EntityStatus string `protobuf:"bytes,2,opt,name=entity_status,json=entityStatus,proto3" json:"entity_status,omitempty" yaml:"entity_status"`
}

func (m *QueryEntityListRequest) Reset()         { *m = QueryEntityListRequest{} }
func (m *QueryEntityListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEntityListRequest) ProtoMessage()    {}
func (*QueryEntityListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f291d1d27dd4d911, []int{0}
}
func (m *QueryEntityListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEntityListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEntityListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEntityListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEntityListRequest.Merge(m, src)
}
func (m *QueryEntityListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEntityListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEntityListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEntityListRequest proto.InternalMessageInfo

func (m *QueryEntityListRequest) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *QueryEntityListRequest) GetEntityStatus() string {
	if m != nil {
		return m.EntityStatus
	}
	return ""
}

// // QueryProjectDocResponse is the response type for the Query/ProjectDoc RPC
// method.
type QueryEntityListResponse struct {
}

func (m *QueryEntityListResponse) Reset()         { *m = QueryEntityListResponse{} }
func (m *QueryEntityListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEntityListResponse) ProtoMessage()    {}
func (*QueryEntityListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f291d1d27dd4d911, []int{1}
}
func (m *QueryEntityListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEntityListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEntityListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEntityListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEntityListResponse.Merge(m, src)
}
func (m *QueryEntityListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEntityListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEntityListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEntityListResponse proto.InternalMessageInfo

// QueryProjectDocRequest is the request type for the Query/ProjectDoc RPC
// method.
type QueryEntityDocRequest struct {
	EntityDid string `protobuf:"bytes,1,opt,name=entity_did,json=entityDid,proto3" json:"entity_did,omitempty" yaml:"entity_did"`
}

func (m *QueryEntityDocRequest) Reset()         { *m = QueryEntityDocRequest{} }
func (m *QueryEntityDocRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEntityDocRequest) ProtoMessage()    {}
func (*QueryEntityDocRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f291d1d27dd4d911, []int{2}
}
func (m *QueryEntityDocRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEntityDocRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEntityDocRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEntityDocRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEntityDocRequest.Merge(m, src)
}
func (m *QueryEntityDocRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEntityDocRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEntityDocRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEntityDocRequest proto.InternalMessageInfo

func (m *QueryEntityDocRequest) GetEntityDid() string {
	if m != nil {
		return m.EntityDid
	}
	return ""
}

// // QueryProjectDocResponse is the response type for the Query/ProjectDoc RPC
// method.
type QueryEntityDocResponse struct {
}

func (m *QueryEntityDocResponse) Reset()         { *m = QueryEntityDocResponse{} }
func (m *QueryEntityDocResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEntityDocResponse) ProtoMessage()    {}
func (*QueryEntityDocResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f291d1d27dd4d911, []int{3}
}
func (m *QueryEntityDocResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEntityDocResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEntityDocResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEntityDocResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEntityDocResponse.Merge(m, src)
}
func (m *QueryEntityDocResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEntityDocResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEntityDocResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEntityDocResponse proto.InternalMessageInfo

type QueryEntityConfigRequest struct {
}

func (m *QueryEntityConfigRequest) Reset()         { *m = QueryEntityConfigRequest{} }
func (m *QueryEntityConfigRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEntityConfigRequest) ProtoMessage()    {}
func (*QueryEntityConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f291d1d27dd4d911, []int{4}
}
func (m *QueryEntityConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEntityConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEntityConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEntityConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEntityConfigRequest.Merge(m, src)
}
func (m *QueryEntityConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEntityConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEntityConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEntityConfigRequest proto.InternalMessageInfo

// // QueryProjectDocResponse is the response type for the Query/ProjectDoc RPC
// method.
type QueryEntityConfigResponse struct {
	Map map[string]string `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" yaml:"config" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *QueryEntityConfigResponse) Reset()         { *m = QueryEntityConfigResponse{} }
func (m *QueryEntityConfigResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEntityConfigResponse) ProtoMessage()    {}
func (*QueryEntityConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f291d1d27dd4d911, []int{5}
}
func (m *QueryEntityConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEntityConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEntityConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEntityConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEntityConfigResponse.Merge(m, src)
}
func (m *QueryEntityConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEntityConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEntityConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEntityConfigResponse proto.InternalMessageInfo

func (m *QueryEntityConfigResponse) GetMap() map[string]string {
	if m != nil {
		return m.Map
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryEntityListRequest)(nil), "kaiju.entity.v1beta1.QueryEntityListRequest")
	proto.RegisterType((*QueryEntityListResponse)(nil), "kaiju.entity.v1beta1.QueryEntityListResponse")
	proto.RegisterType((*QueryEntityDocRequest)(nil), "kaiju.entity.v1beta1.QueryEntityDocRequest")
	proto.RegisterType((*QueryEntityDocResponse)(nil), "kaiju.entity.v1beta1.QueryEntityDocResponse")
	proto.RegisterType((*QueryEntityConfigRequest)(nil), "kaiju.entity.v1beta1.QueryEntityConfigRequest")
	proto.RegisterType((*QueryEntityConfigResponse)(nil), "kaiju.entity.v1beta1.QueryEntityConfigResponse")
	proto.RegisterMapType((map[string]string)(nil), "kaiju.entity.v1beta1.QueryEntityConfigResponse.MapEntry")
}

func init() { proto.RegisterFile("kaiju/entity/v1beta1/query.proto", fileDescriptor_f291d1d27dd4d911) }

var fileDescriptor_f291d1d27dd4d911 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6b, 0x13, 0x41,
	0x18, 0xed, 0x24, 0x54, 0xcc, 0xb4, 0x41, 0x3b, 0x24, 0x71, 0xbb, 0x84, 0x4d, 0x9c, 0x53, 0xc1,
	0x76, 0x87, 0x56, 0xd1, 0x52, 0xf0, 0x12, 0x5b, 0xbc, 0xd8, 0x83, 0xab, 0x27, 0x41, 0xca, 0x24,
	0x19, 0xd7, 0x31, 0xc9, 0xce, 0x36, 0x33, 0x5b, 0x5d, 0x44, 0x10, 0x8f, 0x82, 0x50, 0xf0, 0x47,
	0x78, 0xf7, 0x57, 0x78, 0x2c, 0x78, 0xf1, 0x14, 0x24, 0xf1, 0x17, 0xe4, 0x17, 0x48, 0x66, 0x26,
	0x66, 0x83, 0x91, 0xc6, 0xdb, 0x7e, 0xfb, 0xde, 0xf7, 0xbd, 0x37, 0xdf, 0x9b, 0x81, 0xf5, 0x0e,
	0xe5, 0xaf, 0x12, 0xc2, 0x22, 0xc5, 0x55, 0x4a, 0xce, 0x76, 0x9b, 0x4c, 0xd1, 0x5d, 0x72, 0x9a,
	0xb0, 0x7e, 0xea, 0xc7, 0x7d, 0xa1, 0x04, 0x2a, 0x69, 0x86, 0x6f, 0x18, 0xbe, 0x65, 0xb8, 0xa5,
	0x50, 0x84, 0x42, 0x13, 0xc8, 0xe4, 0xcb, 0x70, 0xdd, 0x6a, 0x28, 0x44, 0xd8, 0x65, 0x84, 0xc6,
	0x9c, 0xd0, 0x28, 0x12, 0x8a, 0x2a, 0x2e, 0x22, 0x69, 0xd1, 0x9b, 0x0b, 0xb5, 0xec, 0x60, 0x4d,
	0xc1, 0xe7, 0x00, 0x56, 0x1e, 0x4f, 0xc4, 0x8f, 0xf4, 0xdf, 0x47, 0x5c, 0xaa, 0x80, 0x9d, 0x26,
	0x4c, 0x2a, 0x74, 0x0f, 0xae, 0x19, 0xea, 0x89, 0x4a, 0x63, 0xe6, 0x80, 0x3a, 0xd8, 0x2a, 0x34,
	0x2a, 0xe3, 0x41, 0x0d, 0xa5, 0xb4, 0xd7, 0x3d, 0xc0, 0x19, 0x10, 0x07, 0xd0, 0x54, 0x4f, 0xd3,
	0x98, 0xa1, 0xfb, 0xb0, 0x68, 0x31, 0xa9, 0xa8, 0x4a, 0xa4, 0x93, 0xd3, 0xad, 0xce, 0x78, 0x50,
	0x2b, 0xcd, 0xb5, 0x1a, 0x18, 0x07, 0xeb, 0xa6, 0x7e, 0x62, 0xca, 0x4d, 0x78, 0xe3, 0x2f, 0x47,
	0x32, 0x16, 0x91, 0x64, 0xf8, 0x18, 0x96, 0x33, 0xd0, 0xa1, 0x68, 0x4d, 0xbd, 0xde, 0x81, 0xd6,
	0xc0, 0x49, 0x9b, 0xb7, 0xad, 0xd5, 0xf2, 0x78, 0x50, 0xdb, 0x98, 0xd3, 0x6b, 0xf3, 0x36, 0x0e,
	0x0a, 0xa6, 0x38, 0xe4, 0x6d, 0xec, 0xcc, 0x9d, 0x5d, 0x8f, 0xb3, 0x42, 0x2e, 0x74, 0x32, 0xc8,
	0x03, 0x11, 0xbd, 0xe0, 0xa1, 0xd5, 0xc2, 0x5f, 0x01, 0xdc, 0x5c, 0x00, 0x9a, 0x4e, 0xf4, 0x1c,
	0xe6, 0x7b, 0x34, 0x76, 0x40, 0x3d, 0xbf, 0xb5, 0xb6, 0xb7, 0xef, 0x2f, 0xca, 0xd2, 0xff, 0x67,
	0xb7, 0x7f, 0x4c, 0xe3, 0xa3, 0x48, 0xf5, 0xd3, 0xc6, 0xc6, 0x78, 0x50, 0x2b, 0x1a, 0xf3, 0x2d,
	0x4d, 0xc1, 0xc1, 0x64, 0xae, 0x7b, 0x17, 0x5e, 0x9d, 0x72, 0xd0, 0x75, 0x98, 0xef, 0xb0, 0xd4,
	0x9c, 0x36, 0x98, 0x7c, 0xa2, 0x12, 0x5c, 0x3d, 0xa3, 0xdd, 0x84, 0x99, 0x8d, 0x07, 0xa6, 0x38,
	0xc8, 0xed, 0x83, 0xbd, 0x2f, 0x79, 0xb8, 0xaa, 0x65, 0xd1, 0x7b, 0x00, 0xe1, 0x6c, 0xb5, 0x68,
	0xfb, 0x52, 0x8b, 0x99, 0x3b, 0xe1, 0xee, 0x2c, 0xc9, 0xb6, 0x6b, 0x2c, 0x7f, 0xf8, 0xfe, 0xeb,
	0x73, 0xee, 0x1a, 0x2a, 0x92, 0xec, 0x4d, 0x44, 0x1f, 0x01, 0x2c, 0xfc, 0xd9, 0x39, 0xba, 0x75,
	0xe9, 0xcc, 0x59, 0xd0, 0xee, 0xf6, 0x72, 0x64, 0xab, 0x8f, 0xb5, 0x7e, 0x15, 0xb9, 0x73, 0xfa,
	0xe4, 0xed, 0xec, 0x3e, 0xbc, 0x43, 0x9f, 0x00, 0x5c, 0xcf, 0x66, 0x81, 0xfc, 0xa5, 0x43, 0x33,
	0x96, 0xc8, 0x7f, 0x86, 0x8c, 0xab, 0xda, 0x55, 0x05, 0x95, 0xe6, 0x5d, 0x99, 0x9c, 0x1b, 0x0f,
	0xbf, 0x0d, 0x3d, 0x70, 0x31, 0xf4, 0xc0, 0xcf, 0xa1, 0x07, 0xce, 0x47, 0xde, 0xca, 0xc5, 0xc8,
	0x5b, 0xf9, 0x31, 0xf2, 0x56, 0x9e, 0xed, 0x84, 0x5c, 0xbd, 0x4c, 0x9a, 0x7e, 0x4b, 0xf4, 0x88,
	0x62, 0x52, 0x8a, 0x7e, 0xc4, 0xd4, 0x6b, 0xd1, 0xef, 0xd8, 0x39, 0x6f, 0xa6, 0x93, 0x26, 0x4f,
	0x52, 0x36, 0xaf, 0xe8, 0x17, 0x7e, 0xfb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x02, 0x31,
	0x6b, 0x72, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	EntityList(ctx context.Context, in *QueryEntityListRequest, opts ...grpc.CallOption) (*QueryEntityListResponse, error)
	EntityDoc(ctx context.Context, in *QueryEntityDocRequest, opts ...grpc.CallOption) (*QueryEntityDocResponse, error)
	EntityConfig(ctx context.Context, in *QueryEntityConfigRequest, opts ...grpc.CallOption) (*QueryEntityConfigResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) EntityList(ctx context.Context, in *QueryEntityListRequest, opts ...grpc.CallOption) (*QueryEntityListResponse, error) {
	out := new(QueryEntityListResponse)
	err := c.cc.Invoke(ctx, "/kaiju.entity.v1beta1.Query/EntityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EntityDoc(ctx context.Context, in *QueryEntityDocRequest, opts ...grpc.CallOption) (*QueryEntityDocResponse, error) {
	out := new(QueryEntityDocResponse)
	err := c.cc.Invoke(ctx, "/kaiju.entity.v1beta1.Query/EntityDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EntityConfig(ctx context.Context, in *QueryEntityConfigRequest, opts ...grpc.CallOption) (*QueryEntityConfigResponse, error) {
	out := new(QueryEntityConfigResponse)
	err := c.cc.Invoke(ctx, "/kaiju.entity.v1beta1.Query/EntityConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	EntityList(context.Context, *QueryEntityListRequest) (*QueryEntityListResponse, error)
	EntityDoc(context.Context, *QueryEntityDocRequest) (*QueryEntityDocResponse, error)
	EntityConfig(context.Context, *QueryEntityConfigRequest) (*QueryEntityConfigResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) EntityList(ctx context.Context, req *QueryEntityListRequest) (*QueryEntityListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityList not implemented")
}
func (*UnimplementedQueryServer) EntityDoc(ctx context.Context, req *QueryEntityDocRequest) (*QueryEntityDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityDoc not implemented")
}
func (*UnimplementedQueryServer) EntityConfig(ctx context.Context, req *QueryEntityConfigRequest) (*QueryEntityConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityConfig not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_EntityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEntityListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EntityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaiju.entity.v1beta1.Query/EntityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EntityList(ctx, req.(*QueryEntityListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EntityDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEntityDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EntityDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaiju.entity.v1beta1.Query/EntityDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EntityDoc(ctx, req.(*QueryEntityDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EntityConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEntityConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EntityConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaiju.entity.v1beta1.Query/EntityConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EntityConfig(ctx, req.(*QueryEntityConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kaiju.entity.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntityList",
			Handler:    _Query_EntityList_Handler,
		},
		{
			MethodName: "EntityDoc",
			Handler:    _Query_EntityDoc_Handler,
		},
		{
			MethodName: "EntityConfig",
			Handler:    _Query_EntityConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaiju/entity/v1beta1/query.proto",
}

func (m *QueryEntityListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEntityListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEntityListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EntityStatus) > 0 {
		i -= len(m.EntityStatus)
		copy(dAtA[i:], m.EntityStatus)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EntityStatus)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EntityType) > 0 {
		i -= len(m.EntityType)
		copy(dAtA[i:], m.EntityType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EntityType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEntityListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEntityListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEntityListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEntityDocRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEntityDocRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEntityDocRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EntityDid) > 0 {
		i -= len(m.EntityDid)
		copy(dAtA[i:], m.EntityDid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EntityDid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEntityDocResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEntityDocResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEntityDocResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEntityConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEntityConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEntityConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEntityConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEntityConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEntityConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Map) > 0 {
		for k := range m.Map {
			v := m.Map[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintQuery(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintQuery(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintQuery(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryEntityListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EntityType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.EntityStatus)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEntityListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEntityDocRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EntityDid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEntityDocResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEntityConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEntityConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Map) > 0 {
		for k, v := range m.Map {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovQuery(uint64(len(k))) + 1 + len(v) + sovQuery(uint64(len(v)))
			n += mapEntrySize + 1 + sovQuery(uint64(mapEntrySize))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryEntityListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEntityListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEntityListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEntityListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEntityListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEntityListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEntityDocRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEntityDocRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEntityDocRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEntityDocResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEntityDocResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEntityDocResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEntityConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEntityConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEntityConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEntityConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEntityConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEntityConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Map", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Map == nil {
				m.Map = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthQuery
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthQuery
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthQuery
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthQuery
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipQuery(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthQuery
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Map[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
