// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kaiju/token/v1beta1/proposal.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SetTokenContractCodes struct {
	Cw20ContractCode      uint64 `protobuf:"varint,1,opt,name=cw20ContractCode,proto3" json:"cw20_contract_code" yaml:"cw20_contract_code"`
	Cw721ContractCode     uint64 `protobuf:"varint,2,opt,name=cw721ContractCode,proto3" json:"cw721_contract_code" yaml:"cw721_contract_code"`
	Kaiju1155ContractCode uint64 `protobuf:"varint,3,opt,name=kaiju1155ContractCode,proto3" json:"kaiju1155_contract_code" yaml:"kaiju1155_contract_code"`
}

func (m *SetTokenContractCodes) Reset()         { *m = SetTokenContractCodes{} }
func (m *SetTokenContractCodes) String() string { return proto.CompactTextString(m) }
func (*SetTokenContractCodes) ProtoMessage()    {}
func (*SetTokenContractCodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce29027ee9d64b1, []int{0}
}
func (m *SetTokenContractCodes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetTokenContractCodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetTokenContractCodes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetTokenContractCodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTokenContractCodes.Merge(m, src)
}
func (m *SetTokenContractCodes) XXX_Size() int {
	return m.Size()
}
func (m *SetTokenContractCodes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTokenContractCodes.DiscardUnknown(m)
}

var xxx_messageInfo_SetTokenContractCodes proto.InternalMessageInfo

func (m *SetTokenContractCodes) GetCw20ContractCode() uint64 {
	if m != nil {
		return m.Cw20ContractCode
	}
	return 0
}

func (m *SetTokenContractCodes) GetCw721ContractCode() uint64 {
	if m != nil {
		return m.Cw721ContractCode
	}
	return 0
}

func (m *SetTokenContractCodes) GetKaiju1155ContractCode() uint64 {
	if m != nil {
		return m.Kaiju1155ContractCode
	}
	return 0
}

func init() {
	proto.RegisterType((*SetTokenContractCodes)(nil), "kaiju.token.v1beta1.SetTokenContractCodes")
}

func init() {
	proto.RegisterFile("kaiju/token/v1beta1/proposal.proto", fileDescriptor_9ce29027ee9d64b1)
}

var fileDescriptor_9ce29027ee9d64b1 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xca, 0x4e, 0xcc, 0xcc,
	0x2a, 0xd5, 0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0xd3, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc8, 0x2f, 0x4e, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x06, 0xab, 0xd1, 0x03, 0xab, 0xd1, 0x83, 0xaa, 0x91, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0xcb,
	0xeb, 0x83, 0x58, 0x10, 0xa5, 0x52, 0xf2, 0xd8, 0x8c, 0x83, 0x68, 0x04, 0x2b, 0x50, 0xba, 0xc4,
	0xc4, 0x25, 0x1a, 0x9c, 0x5a, 0x12, 0x02, 0x12, 0x72, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e,
	0x71, 0xce, 0x4f, 0x49, 0x2d, 0x16, 0x8a, 0xe7, 0x12, 0x48, 0x2e, 0x37, 0x32, 0x40, 0x16, 0x94,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x71, 0x32, 0x7e, 0x75, 0x4f, 0x5e, 0x08, 0x24, 0x17, 0x9f, 0x0c,
	0x95, 0x8c, 0x4f, 0xce, 0x4f, 0x49, 0xfd, 0x74, 0x4f, 0x5e, 0xb2, 0x32, 0x31, 0x37, 0xc7, 0x4a,
	0x09, 0x53, 0x4e, 0x29, 0x08, 0xc3, 0x30, 0xa1, 0x64, 0x2e, 0xc1, 0xe4, 0x72, 0x73, 0x23, 0x43,
	0x14, 0x1b, 0x98, 0xc0, 0x36, 0x98, 0xbe, 0xba, 0x27, 0x2f, 0x0c, 0x96, 0xc4, 0xb0, 0x42, 0x0a,
	0x66, 0x05, 0x86, 0xa4, 0x52, 0x10, 0xa6, 0x79, 0x42, 0xc5, 0x5c, 0xa2, 0xe0, 0x20, 0x30, 0x34,
	0x34, 0x35, 0x45, 0xb1, 0x88, 0x19, 0x6c, 0x91, 0xed, 0xab, 0x7b, 0xf2, 0xe2, 0x70, 0x05, 0x18,
	0x96, 0xc9, 0x41, 0x2c, 0xc3, 0xa1, 0x40, 0x29, 0x08, 0xbb, 0xd9, 0x4e, 0x6e, 0x27, 0x1e, 0xc9,
	0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e,
	0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x93, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97,
	0x9c, 0x9f, 0xab, 0x5f, 0x92, 0x5a, 0x5c, 0x9c, 0x5f, 0x94, 0x97, 0x5a, 0x52, 0x9e, 0x5f, 0x94,
	0xad, 0x0f, 0x89, 0xa8, 0x0a, 0x68, 0x54, 0x95, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0xe3,
	0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x02, 0x63, 0xdf, 0x15, 0x02, 0x00, 0x00,
}

func (m *SetTokenContractCodes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetTokenContractCodes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetTokenContractCodes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Kaiju1155ContractCode != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.Kaiju1155ContractCode))
		i--
		dAtA[i] = 0x18
	}
	if m.Cw721ContractCode != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.Cw721ContractCode))
		i--
		dAtA[i] = 0x10
	}
	if m.Cw20ContractCode != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.Cw20ContractCode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintProposal(dAtA []byte, offset int, v uint64) int {
	offset -= sovProposal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SetTokenContractCodes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cw20ContractCode != 0 {
		n += 1 + sovProposal(uint64(m.Cw20ContractCode))
	}
	if m.Cw721ContractCode != 0 {
		n += 1 + sovProposal(uint64(m.Cw721ContractCode))
	}
	if m.Kaiju1155ContractCode != 0 {
		n += 1 + sovProposal(uint64(m.Kaiju1155ContractCode))
	}
	return n
}

func sovProposal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProposal(x uint64) (n int) {
	return sovProposal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SetTokenContractCodes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetTokenContractCodes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetTokenContractCodes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cw20ContractCode", wireType)
			}
			m.Cw20ContractCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cw20ContractCode |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cw721ContractCode", wireType)
			}
			m.Cw721ContractCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cw721ContractCode |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kaiju1155ContractCode", wireType)
			}
			m.Kaiju1155ContractCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kaiju1155ContractCode |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProposal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProposal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProposal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProposal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProposal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProposal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProposal = fmt.Errorf("proto: unexpected end of group")
)
