// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kaiju/token/v1beta1/token.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_tessornetwork_kaiju_x_iid_types "github.com/tessornetwork/kaiju/x/iid/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ContractType int32

const (
	ContractType_CW20      ContractType = 0
	ContractType_CW721     ContractType = 1
	ContractType_KAIJU1155 ContractType = 2
)

var ContractType_name = map[int32]string{
	0: "CW20",
	1: "CW721",
	2: "KAIJU1155",
}

var ContractType_value = map[string]int32{
	"CW20":      0,
	"CW721":     1,
	"KAIJU1155": 2,
}

func (x ContractType) String() string {
	return proto.EnumName(ContractType_name, int32(x))
}

func (ContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b2e7edc91a060a5b, []int{0}
}

type Contract struct {
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address" yaml:"address"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e7edc91a060a5b, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return m.Size()
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contract) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Params struct {
	Cw20ContractCode      string `protobuf:"bytes,1,opt,name=cw20ContractCode,proto3" json:"cw20_contract_code" yaml:"cw20_contract_code"`
	Cw721ContractCode     string `protobuf:"bytes,2,opt,name=cw721ContractCode,proto3" json:"cw721_contract_code" yaml:"cw721_contract_code"`
	Kaiju1155ContractCode string `protobuf:"bytes,3,opt,name=kaiju1155ContractCode,proto3" json:"kaiju1155_contract_code" yaml:"kaiju1155_contract_code"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e7edc91a060a5b, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type TokenMinter struct {
	MinterDid       github_com_tessornetwork_kaiju_x_iid_types.DIDFragment `protobuf:"bytes,1,opt,name=minterDid,proto3,casttype=github.com/tessornetwork/kaiju/x/iid/types.DIDFragment" json:"minter_did" yaml:"minter_did"`
	MinterAddress   string                                                 `protobuf:"bytes,2,opt,name=minterAddress,proto3" json:"minter_address" yaml:"minter_address"`
	ContractAddress string                                                 `protobuf:"bytes,3,opt,name=contractAddress,proto3" json:"contract_address" yaml:"contract_address"`
	ContractType    ContractType                                           `protobuf:"varint,4,opt,name=contractType,proto3,enum=kaiju.token.v1beta1.ContractType" json:"contract_type" yaml:"contract_type"`
	Name            string                                                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name" yaml:"name"`
	Description     string                                                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description" yaml:"description"`
}

func (m *TokenMinter) Reset()         { *m = TokenMinter{} }
func (m *TokenMinter) String() string { return proto.CompactTextString(m) }
func (*TokenMinter) ProtoMessage()    {}
func (*TokenMinter) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e7edc91a060a5b, []int{2}
}
func (m *TokenMinter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenMinter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenMinter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenMinter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMinter.Merge(m, src)
}
func (m *TokenMinter) XXX_Size() int {
	return m.Size()
}
func (m *TokenMinter) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMinter.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMinter proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("kaiju.token.v1beta1.ContractType", ContractType_name, ContractType_value)
	proto.RegisterType((*Contract)(nil), "kaiju.token.v1beta1.Contract")
	proto.RegisterType((*Params)(nil), "kaiju.token.v1beta1.Params")
	proto.RegisterType((*TokenMinter)(nil), "kaiju.token.v1beta1.TokenMinter")
}

func init() { proto.RegisterFile("kaiju/token/v1beta1/token.proto", fileDescriptor_b2e7edc91a060a5b) }

var fileDescriptor_b2e7edc91a060a5b = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x4f, 0xd4, 0x40,
	0x1c, 0xdd, 0xd6, 0x05, 0xd9, 0xe1, 0x8f, 0xcb, 0x00, 0x61, 0x25, 0xb1, 0x83, 0x63, 0x4c, 0x50,
	0x4c, 0x4b, 0x4b, 0x90, 0x84, 0xc4, 0x03, 0x2c, 0xc1, 0xa0, 0x31, 0xd1, 0x06, 0x43, 0x34, 0x31,
	0x9b, 0xd2, 0x4e, 0x96, 0x8a, 0xed, 0x6c, 0xda, 0x41, 0x24, 0x7e, 0x01, 0x8f, 0x7e, 0x04, 0x4f,
	0x7e, 0x16, 0xbd, 0x71, 0xf4, 0x34, 0x31, 0x70, 0xeb, 0xb1, 0x47, 0x4f, 0xa6, 0x33, 0xed, 0xee,
	0x76, 0x8b, 0xf1, 0xd6, 0x79, 0xef, 0xcd, 0x7b, 0xed, 0x6f, 0x5e, 0x07, 0xa0, 0x13, 0xc7, 0x7f,
	0x7f, 0x6a, 0x30, 0x7a, 0x42, 0x42, 0xe3, 0xa3, 0x79, 0x44, 0x98, 0x63, 0xca, 0x95, 0xde, 0x8b,
	0x28, 0xa3, 0x70, 0x4e, 0x08, 0x74, 0x09, 0xe5, 0x82, 0xa5, 0xf9, 0x2e, 0xed, 0x52, 0xc1, 0x1b,
	0xd9, 0x93, 0x94, 0xe2, 0x63, 0x30, 0xd1, 0xa6, 0x21, 0x8b, 0x1c, 0x97, 0xc1, 0x7b, 0x40, 0xf5,
	0xbd, 0x96, 0xb2, 0xac, 0xac, 0x34, 0x76, 0xe6, 0x12, 0x8e, 0x54, 0xdf, 0x4b, 0x39, 0x6a, 0x9c,
	0x3b, 0xc1, 0x87, 0x2d, 0xec, 0x7b, 0xd8, 0x56, 0x7d, 0x0f, 0x6e, 0x82, 0x9b, 0x8e, 0xe7, 0x45,
	0x24, 0x8e, 0x5b, 0xaa, 0x50, 0xde, 0x49, 0x38, 0x2a, 0xa0, 0x94, 0xa3, 0x19, 0x29, 0xcf, 0x01,
	0x6c, 0x17, 0x14, 0xfe, 0xa9, 0x82, 0xf1, 0x97, 0x4e, 0xe4, 0x04, 0x31, 0xec, 0x80, 0xa6, 0x7b,
	0x66, 0xad, 0x15, 0xc1, 0x6d, 0xea, 0x91, 0x3c, 0x76, 0x3d, 0xe1, 0x08, 0x66, 0x5c, 0xc7, 0xcd,
	0xc9, 0x8e, 0x4b, 0x3d, 0x92, 0x72, 0x74, 0x5b, 0xfa, 0x56, 0x39, 0x6c, 0x57, 0xcc, 0xa0, 0x0b,
	0x66, 0xdd, 0xb3, 0x4d, 0xcb, 0x2c, 0x25, 0xc8, 0xd7, 0xdd, 0x48, 0x38, 0x9a, 0x13, 0x64, 0x25,
	0x62, 0xa9, 0x88, 0xa8, 0x90, 0xd8, 0xae, 0xfa, 0xc1, 0x18, 0x2c, 0x88, 0x39, 0x9b, 0xe6, 0xc6,
	0x46, 0x29, 0xe8, 0x86, 0x08, 0x7a, 0x92, 0x70, 0xb4, 0xd8, 0x17, 0x54, 0xc2, 0x34, 0x19, 0xf6,
	0x0f, 0x01, 0xb6, 0xaf, 0xf7, 0xde, 0xaa, 0x7f, 0xf9, 0x86, 0x6a, 0xf8, 0x7b, 0x1d, 0x4c, 0x1e,
	0x64, 0xa7, 0xfb, 0xc2, 0x0f, 0x19, 0x89, 0xe0, 0x67, 0xd0, 0x08, 0xc4, 0xd3, 0x6e, 0xff, 0x00,
	0xdf, 0x25, 0x1c, 0x01, 0x09, 0x76, 0x3c, 0x71, 0x90, 0xb3, 0x32, 0x71, 0x80, 0xe1, 0x3f, 0x1c,
	0x3d, 0xee, 0xfa, 0xec, 0xf8, 0xf4, 0x48, 0x77, 0x69, 0x60, 0x30, 0x12, 0xc7, 0x34, 0x0a, 0x09,
	0x3b, 0xa3, 0xd1, 0x89, 0x21, 0x4b, 0xf6, 0xc9, 0xf0, 0x7d, 0xcf, 0x60, 0xe7, 0x3d, 0x12, 0xeb,
	0xbb, 0xfb, 0xbb, 0x7b, 0x91, 0xd3, 0x0d, 0x48, 0xc8, 0xec, 0x41, 0x1e, 0x7c, 0x05, 0xa6, 0xe5,
	0x62, 0xbb, 0xd4, 0x8b, 0xd5, 0x84, 0xa3, 0x99, 0x3c, 0x6c, 0x50, 0x8f, 0x85, 0xd2, 0x4b, 0xf4,
	0x5b, 0x52, 0x76, 0x80, 0x6f, 0xc0, 0xad, 0x62, 0x1c, 0x85, 0xa9, 0x1c, 0xaa, 0x91, 0x70, 0xd4,
	0xec, 0x4f, 0x6a, 0x60, 0xbb, 0x98, 0x1f, 0xdd, 0x08, 0x83, 0xed, 0x51, 0x1f, 0xd8, 0x03, 0x53,
	0x05, 0x74, 0x70, 0xde, 0x23, 0xad, 0xfa, 0xb2, 0xb2, 0x32, 0x63, 0xdd, 0xd5, 0xaf, 0xf9, 0x65,
	0xf4, 0xf6, 0x90, 0x70, 0xe7, 0x41, 0xc2, 0xd1, 0x74, 0x3f, 0x20, 0x9b, 0x48, 0xca, 0xd1, 0xfc,
	0x48, 0x6e, 0x06, 0x63, 0xbb, 0x94, 0x00, 0x57, 0x41, 0x3d, 0x74, 0x02, 0xd2, 0x1a, 0x13, 0x5f,
	0xb0, 0x98, 0x70, 0x24, 0xd6, 0x29, 0x47, 0x93, 0x72, 0x77, 0xb6, 0xc2, 0xb6, 0x00, 0xe1, 0x53,
	0x30, 0xe9, 0x91, 0xd8, 0x8d, 0xfc, 0x1e, 0xf3, 0x69, 0xd8, 0x1a, 0x17, 0x7b, 0xee, 0x27, 0x1c,
	0x0d, 0xc3, 0x29, 0x47, 0x50, 0x6e, 0x1d, 0x02, 0xb1, 0x3d, 0x2c, 0x91, 0x45, 0x79, 0x68, 0x81,
	0xa9, 0xe1, 0x8f, 0x80, 0x13, 0xa0, 0xde, 0x3e, 0xb4, 0xd6, 0x9a, 0x35, 0xd8, 0x00, 0x63, 0xed,
	0xc3, 0x4d, 0xcb, 0x6c, 0x2a, 0x70, 0x1a, 0x34, 0x9e, 0x6f, 0xef, 0x3f, 0x7b, 0x9d, 0x95, 0xad,
	0xa9, 0xee, 0xec, 0xfd, 0xb8, 0xd4, 0x94, 0x8b, 0x4b, 0x4d, 0xf9, 0x7d, 0xa9, 0x29, 0x5f, 0xaf,
	0xb4, 0xda, 0xc5, 0x95, 0x56, 0xfb, 0x75, 0xa5, 0xd5, 0xde, 0x3e, 0xfa, 0x6f, 0x59, 0xe4, 0x9d,
	0x24, 0xea, 0x72, 0x34, 0x2e, 0x6e, 0x98, 0xf5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x13,
	0x57, 0x73, 0xaf, 0x04, 0x00, 0x00,
}

func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Kaiju1155ContractCode) > 0 {
		i -= len(m.Kaiju1155ContractCode)
		copy(dAtA[i:], m.Kaiju1155ContractCode)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Kaiju1155ContractCode)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Cw721ContractCode) > 0 {
		i -= len(m.Cw721ContractCode)
		copy(dAtA[i:], m.Cw721ContractCode)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Cw721ContractCode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Cw20ContractCode) > 0 {
		i -= len(m.Cw20ContractCode)
		copy(dAtA[i:], m.Cw20ContractCode)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Cw20ContractCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenMinter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenMinter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenMinter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ContractType != 0 {
		i = encodeVarintToken(dAtA, i, uint64(m.ContractType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintToken(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MinterAddress) > 0 {
		i -= len(m.MinterAddress)
		copy(dAtA[i:], m.MinterAddress)
		i = encodeVarintToken(dAtA, i, uint64(len(m.MinterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MinterDid) > 0 {
		i -= len(m.MinterDid)
		copy(dAtA[i:], m.MinterDid)
		i = encodeVarintToken(dAtA, i, uint64(len(m.MinterDid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Cw20ContractCode)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Cw721ContractCode)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Kaiju1155ContractCode)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	return n
}

func (m *TokenMinter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MinterDid)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.MinterAddress)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	if m.ContractType != 0 {
		n += 1 + sovToken(uint64(m.ContractType))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	return n
}

func sovToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozToken(x uint64) (n int) {
	return sovToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cw20ContractCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cw20ContractCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cw721ContractCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cw721ContractCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kaiju1155ContractCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kaiju1155ContractCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenMinter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenMinter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenMinter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinterDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinterDid = github_com_tessornetwork_kaiju_x_iid_types.DIDFragment(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractType", wireType)
			}
			m.ContractType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractType |= ContractType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupToken = fmt.Errorf("proto: unexpected end of group")
)
